package tv.ninekpro.desktop.ui

import androidx.compose.runtime.compositionLocalOf

/** Same texts as the Android app (EN / AR / HE). */
object Strings {
    val EN = mapOf(
    "reorder_hint" to "Drag to reorder · Done when finished",
    "app_name" to "9K Pro TV",
    "login_title" to "Sign in",
    "username" to "Username",
    "password" to "Password",
    "sign_in" to "Sign in",
    "code_login" to "Sign in with activation code",
    "code" to "6-digit code",
    "add_playlist" to "Add my own playlist",
    "playlist_name" to "Playlist name",
    "host" to "Server URL (http://host:port)",
    "m3u_url" to "M3U link",
    "xtream" to "Xtream Codes",
    "m3u" to "M3U link",
    "save" to "Save",
    "cancel" to "Cancel",
    "live" to "Live TV",
    "movies" to "Movies",
    "series" to "Series",
    "favorites" to "Favorites",
    "continue_watching" to "Continue watching",
    "settings" to "Settings",
    "downloads" to "Downloads",
    "search" to "Search",
    "crash_trial" to "Crash Trial",
    "crash_trial_hint" to "Server down? Get a temporary playlist now.",
    "renew" to "Renew via WhatsApp",
    "expires_in" to "Your subscription ends in %1\$d days",
    "expired" to "Your subscription has expired",
    "playlists" to "Playlists",
    "logout" to "Sign out",
    "language" to "Language",
    "theme" to "Theme",
    "theme_navy" to "Navy",
    "theme_light" to "Light",
    "theme_amoled" to "AMOLED black",
    "subtitles" to "Subtitles",
    "subtitle_size" to "Subtitle size",
    "audio" to "Audio",
    "aspect" to "Aspect",
    "speed" to "Speed",
    "none" to "None",
    "pick_file" to "Pick subtitle file",
    "download" to "Download",
    "download_season" to "Download season",
    "play" to "Play",
    "resume" to "Resume",
    "episodes" to "Episodes",
    "season" to "Season %1\$d",
    "all" to "All",
    "loading" to "Loading…",
    "error_network" to "Could not reach the server",
    "error_login" to "Wrong username or password",
    "error_blocked" to "This account is blocked. Contact your provider.",
    "error_expired" to "Subscription expired. Please renew.",
    "hide" to "Hide",
    "unhide" to "Unhide",
    "move_up" to "Move up",
    "move_down" to "Move down",
    "move_top" to "Move to top",
    "show_hidden" to "Show hidden",
    "next_episode" to "Next episode",
    "sort" to "Sort",
    "sort_default" to "Default",
    "sort_az" to "A–Z",
    "sort_newest" to "Newest",
    "sort_rating" to "Rating",
    "support" to "Support",
    "messages" to "Messages",
    "ok" to "OK",
    "retry" to "Retry",
    "no_items" to "Nothing here yet",
    "wifi_only" to "Download on Wi-Fi only",
    "delete" to "Delete",
    "playing_error" to "This stream could not be played. Trying another server…",
    "app_version" to "Version",
    "catchup" to "Catch-up",
    "now" to "Now",
    "next" to "Next",
    "lock_pin" to "Lock with PIN",
    "unlock" to "Remove lock",
    "enter_pin" to "Enter PIN",
    "set_pin" to "Parental PIN (4 digits)",
    "wrong_pin" to "Wrong PIN",
    "recently_added" to "Recently added",
    "channel" to "Channel",
    "no_epg" to "No guide data",
    "home_tab" to "Home",
    "lock" to "Lock",
    "add_favorite" to "Add to Favorite",
    "remove_favorite" to "Remove Favorite",
    "parental" to "Parental Control",
    "parental_hint" to "Long-press a category → Lock. Locked categories ask for this PIN.",
    "clear_history" to "Clear History",
    "update_now" to "Update Now",
    "update_hint" to "Re-download the channel, movie and series lists from the server.",
    "hidden_hint" to "Hidden channels and categories are shown again with a dim look; long-press → Unhide.",
    "recently_viewed" to "Recently Viewed",
    "multi_screen" to "Multi Screen",
    "expires" to "expires",
    "cast" to "Cast",
    "start_over" to "Start over",
    "trailer" to "Trailer",
    "channels" to "Channels",
    "live_format" to "Live Stream Format",
    "external_player" to "Open in external player",
    "pick_channel" to "Pick a channel",
    "change_language" to "Change Language",
    "change_layout" to "Change Layout",
    "hide_live" to "Hide Live Categories",
    "hide_vod" to "Hide Vod Categories",
    "hide_series" to "Hide Series Categories",
    "clear_channels" to "Clear History Channels",
    "clear_movies" to "Clear History Movies",
    "clear_series" to "Clear History Series",
    "live_sort" to "Live Channel Sort",
    "change_player" to "Change Player",
    "external_players" to "External players",
    "automatic" to "Automatic",
    "time_format" to "Time Format",
    "subtitle_settings" to "Subtitle Settings",
    "device_type" to "Select Device Type",
    "parental_onoff" to "Parental Control ON/OFF",
    "layout_large" to "Large",
    "layout_normal" to "Normal",
    "layout_compact" to "Compact",
    "sort_number" to "By number",
    "format_hint" to "Auto tries HLS first and switches to MPEG-TS when a channel fails.",
    "player_hint" to "Auto uses ExoPlayer and switches to VLC when a stream cannot be played.",
    "external_hint" to "Always open streams in an external player (VLC / MX Player)",
    "automatic_hint" to "Refresh channel lists automatically every 6 hours",
    "subtitle_lang" to "Preferred subtitle language",
    "subtitle_color" to "Subtitle color",
    "crash_fix" to "Crash Fix",
    "crash_fix_q" to "Your server is down? Switch to a temporary server for 24 hours. After that the app returns to your account by itself.",
    "crash_fix_active" to "Crash Fix is active — back to your account in %1\$d h",
    "crash_fix_on" to "Temporary server activated for 24 hours",
    "crash_fix_off" to "Crash Fix is not available right now — contact support",
    "back_now" to "Back now",
    "exit_q" to "Exit 9K Pro TV?",
    "exit" to "Exit",
    "guide" to "Guide",
    "report_problem" to "Report a problem",
    "report_sent" to "Report sent to your provider",
    "trying_server" to "Trying server %1\$d…",
    "stream_info" to "Stream info",
    "resume_q" to "Continue where you left off?",
    "pause" to "Pause",
    "more" to "More",
    "search_online" to "Search online",
    "subs_off_hint" to "Online subtitle search is off — your provider can enable it in the panel (OpenSubtitles key).",
    "welcome_to" to "Welcome to %1\$s",
    "server_down" to "Your server is not responding right now.",
    "n_channels" to "%1\$d channels",
    "n_titles" to "%1\$d titles",
    "n_shows" to "%1\$d shows",
    "min_left" to "%1\$d min left",
    "new_this_week" to "New this week",
    "open" to "Open",
    "sports" to "Sports",
    "yesterday" to "Yesterday",
    "today" to "Today",
    "tomorrow" to "Tomorrow",
    "football_off" to "Match day is not enabled — your provider can turn it on in the panel.",
    "no_matches" to "No matches on this day.",
    "live_now" to "Live now",
    "matches_today" to "Matches today",
    "match_channels" to "Channels showing this match",
    "match_no_channel" to "No channel found in the guide yet — try the Sports category in Live TV.",
    "match_soon" to "Kick-off in 5 minutes — tap to open",
    "change_server" to "Change server",
    "servers" to "Servers",
    "server_n" to "Server %1\$d",
    "one_server_only" to "Only one server is set up for this account.",
    "downloaded_on" to "Downloaded",
    "downloading" to "Downloading",
    "download_failed" to "Failed",
    "remove" to "Remove",
    "change_playlist" to "Change playlist",
    "one_playlist_only" to "Only one playlist on this account.",
    "connected" to "Connected",
    "protected_pl" to "Protected",
    "mac_address" to "MAC address",
    "device_key" to "Device key",
    "use_code" to "Have an activation code?",
    "use_password" to "Use username & password",
    "need_subscription" to "Need a subscription?",
    "support_hint" to "Chat with %1\$s on WhatsApp — send your MAC address and we activate this device.",
    "scan_whatsapp" to "Scan with your phone camera to open the chat",
    "chat_whatsapp" to "Chat on WhatsApp",
    "no_whatsapp" to "Support number not set yet.",
    "crash_fix_expired" to "Your subscription has expired — renew first.",
    "crash_fix_wait" to "Please wait %1\$d minutes before trying again.",
    "crash_fix_limit" to "Crash Fix limit reached (%1\$d per day). Try again tomorrow.",
    "crash_fix_refused" to "The backup server did not answer — try again in a minute.",
    "switched_to" to "Switched to %1\$s",
    "preparing_line" to "Preparing your temporary server, channels arrive in a moment…",
    "rating" to "Rating",
    "year" to "Year",
    "length" to "Length",
    "director" to "Director",
    "seasons" to "Seasons",
    "refreshing" to "Refreshing…",
    "whatsapp_support" to "WhatsApp support",
    "loading_playlist" to "Loading your playlist…",
    "prog_soon" to "Starts in 5 minutes — tap to watch",
    "reminder_set" to "Reminder set",
    "reminder_off" to "Reminder removed",
    "speed_test" to "Speed test",
    "speed_start" to "Start test",
    "speed_testing" to "Testing… downloading from your server",
    "speed_ping" to "Server answer",
    "speed_download" to "Download speed",
    "speed_verdict_bad" to "Too slow for live TV — check the Wi-Fi or try another server",
    "speed_verdict_sd" to "OK for SD channels; HD may buffer",
    "speed_verdict_hd" to "Good for HD",
    "speed_verdict_4k" to "Excellent — 4K ready",
    "speed_fail" to "Could not reach the server",
    "speed_internet" to "Internet speed",
    "speed_server" to "Your server",
    "speed_jitter" to "jitter",
    "speed_again" to "Test again",
    "speed_no_internet" to "No internet — check the Wi-Fi or data connection",
    "speed_server_ok" to "Streams play normally",
    "speed_server_bad" to "No stream received — try another server",
    "speed_step_ping" to "Server answer",
    "speed_step_down" to "Internet speed",
    "speed_step_stream" to "Server stream",
    "speed_hint" to "Measures your internet line and checks that your server delivers video. Takes about 15 seconds.",
    "record" to "Record",
    "recording" to "Recording…",
    "stop_recording" to "Stop",
    "recording_saved" to "Recording saved in Downloads",
    "record_scheduled" to "Recording scheduled (long-press again to cancel)",
    "record_unscheduled" to "Recording cancelled",
    "open_full" to "Full screen",
    "win_close" to "Close",
    "win_min" to "Minimize",
    "shortcuts" to "Keys: F full screen · Space pause · ↑↓ channel · 0-9 number · Esc back · M mute · S subtitles · A audio",
    "checking_update" to "Checking for updates…",
    "updated" to "Updated",
    "device_id" to "Device ID",
    "waiting_line" to "This computer is registered. Ask your seller to add a playlist to this Device ID — it will appear here by itself.",
    "copy" to "Copy",
    "copied" to "Copied",
    "mac_id_hint" to "Send this Device ID to your seller"
)
    val AR = mapOf(
    "reorder_hint" to "اسحب لإعادة الترتيب · تم عند الانتهاء",
    "login_title" to "تسجيل الدخول",
    "username" to "اسم المستخدم",
    "password" to "كلمة المرور",
    "sign_in" to "دخول",
    "code_login" to "الدخول برمز التفعيل",
    "code" to "رمز من 6 أرقام",
    "add_playlist" to "إضافة قائمة خاصة بي",
    "playlist_name" to "اسم القائمة",
    "host" to "رابط السيرفر (http://host:port)",
    "m3u_url" to "رابط M3U",
    "xtream" to "Xtream Codes",
    "m3u" to "رابط M3U",
    "save" to "حفظ",
    "cancel" to "إلغاء",
    "live" to "البث المباشر",
    "movies" to "أفلام",
    "series" to "مسلسلات",
    "favorites" to "المفضلة",
    "continue_watching" to "متابعة المشاهدة",
    "settings" to "الإعدادات",
    "downloads" to "التنزيلات",
    "search" to "بحث",
    "crash_trial" to "تجربة طوارئ",
    "crash_trial_hint" to "السيرفر معطّل؟ احصل على قائمة مؤقتة الآن.",
    "renew" to "تجديد عبر واتساب",
    "expires_in" to "اشتراكك ينتهي خلال %1\$d يوم",
    "expired" to "انتهى اشتراكك",
    "playlists" to "القوائم",
    "logout" to "تسجيل الخروج",
    "language" to "اللغة",
    "theme" to "المظهر",
    "theme_navy" to "كحلي",
    "theme_light" to "فاتح",
    "theme_amoled" to "أسود AMOLED",
    "subtitles" to "الترجمة",
    "subtitle_size" to "حجم الترجمة",
    "audio" to "الصوت",
    "aspect" to "أبعاد الصورة",
    "speed" to "السرعة",
    "none" to "بدون",
    "pick_file" to "اختر ملف ترجمة",
    "download" to "تنزيل",
    "download_season" to "تنزيل الموسم",
    "play" to "تشغيل",
    "resume" to "متابعة",
    "episodes" to "الحلقات",
    "season" to "الموسم %1\$d",
    "all" to "الكل",
    "loading" to "جارٍ التحميل…",
    "error_network" to "تعذر الوصول إلى السيرفر",
    "error_login" to "اسم المستخدم أو كلمة المرور خاطئة",
    "error_blocked" to "هذا الحساب محظور. تواصل مع المزوّد.",
    "error_expired" to "انتهى الاشتراك. يرجى التجديد.",
    "hide" to "إخفاء",
    "unhide" to "إظهار",
    "move_up" to "نقل للأعلى",
    "move_down" to "نقل للأسفل",
    "move_top" to "نقل إلى البداية",
    "show_hidden" to "إظهار المخفي",
    "next_episode" to "الحلقة التالية",
    "sort" to "ترتيب",
    "sort_default" to "افتراضي",
    "sort_az" to "أبجدي",
    "sort_newest" to "الأحدث",
    "sort_rating" to "التقييم",
    "support" to "الدعم",
    "messages" to "الرسائل",
    "ok" to "حسناً",
    "retry" to "إعادة المحاولة",
    "no_items" to "لا يوجد شيء هنا بعد",
    "wifi_only" to "التنزيل عبر Wi-Fi فقط",
    "delete" to "حذف",
    "playing_error" to "تعذر تشغيل هذه القناة. جارٍ تجربة سيرفر آخر…",
    "app_version" to "الإصدار",
    "catchup" to "إعادة المشاهدة",
    "now" to "الآن",
    "next" to "التالي",
    "lock_pin" to "قفل برمز",
    "unlock" to "إزالة القفل",
    "enter_pin" to "أدخل الرمز",
    "set_pin" to "رمز الحماية (4 أرقام)",
    "wrong_pin" to "رمز خاطئ",
    "recently_added" to "أضيف حديثاً",
    "channel" to "قناة",
    "no_epg" to "لا يوجد دليل برامج",
    "home_tab" to "الرئيسية",
    "lock" to "المقفول",
    "add_favorite" to "أضف للمفضلة",
    "remove_favorite" to "إزالة من المفضلة",
    "parental" to "الرقابة الأبوية",
    "parental_hint" to "اضغط مطولاً على فئة ← قفل. الفئات المقفولة تطلب هذا الرمز.",
    "clear_history" to "مسح السجل",
    "update_now" to "تحديث الآن",
    "update_hint" to "إعادة تحميل قوائم القنوات والأفلام والمسلسلات من السيرفر.",
    "hidden_hint" to "العناصر المخفية تظهر باهتة؛ اضغط مطولاً ← إظهار.",
    "recently_viewed" to "شوهد مؤخراً",
    "multi_screen" to "شاشات متعددة",
    "expires" to "ينتهي",
    "cast" to "الممثلون",
    "start_over" to "من البداية",
    "trailer" to "الإعلان",
    "channels" to "القنوات",
    "live_format" to "صيغة البث المباشر",
    "external_player" to "فتح بمشغل خارجي",
    "pick_channel" to "اختر قناة",
    "change_language" to "تغيير اللغة",
    "change_layout" to "تغيير التخطيط",
    "hide_live" to "إخفاء فئات البث",
    "hide_vod" to "إخفاء فئات الأفلام",
    "hide_series" to "إخفاء فئات المسلسلات",
    "clear_channels" to "مسح سجل القنوات",
    "clear_movies" to "مسح سجل الأفلام",
    "clear_series" to "مسح سجل المسلسلات",
    "live_sort" to "ترتيب القنوات",
    "change_player" to "تغيير المشغل",
    "external_players" to "مشغلات خارجية",
    "automatic" to "تلقائي",
    "time_format" to "صيغة الوقت",
    "subtitle_settings" to "إعدادات الترجمة",
    "device_type" to "نوع الجهاز",
    "parental_onoff" to "الرقابة الأبوية تشغيل/إيقاف",
    "layout_large" to "كبير",
    "layout_normal" to "عادي",
    "layout_compact" to "مضغوط",
    "sort_number" to "حسب الرقم",
    "format_hint" to "تلقائي يجرب HLS أولاً ثم MPEG-TS عند فشل القناة.",
    "player_hint" to "تلقائي يستخدم ExoPlayer ويتحول إلى VLC عند تعذر التشغيل.",
    "external_hint" to "فتح البث دائماً بمشغل خارجي (VLC / MX Player)",
    "automatic_hint" to "تحديث القوائم تلقائياً كل 6 ساعات",
    "subtitle_lang" to "لغة الترجمة المفضلة",
    "subtitle_color" to "لون الترجمة",
    "crash_fix" to "إصلاح العطل",
    "crash_fix_q" to "السيرفر معطل؟ سيتم التحويل إلى سيرفر مؤقت لمدة 24 ساعة، وبعدها يعود التطبيق إلى حسابك تلقائياً.",
    "crash_fix_active" to "إصلاح العطل مفعّل — العودة إلى حسابك خلال %1\$d ساعة",
    "crash_fix_on" to "تم تفعيل السيرفر المؤقت لمدة 24 ساعة",
    "crash_fix_off" to "إصلاح العطل غير متاح حالياً — تواصل مع الدعم",
    "back_now" to "العودة الآن",
    "exit_q" to "الخروج من 9K Pro TV؟",
    "exit" to "خروج",
    "guide" to "دليل البرامج",
    "report_problem" to "الإبلاغ عن مشكلة",
    "report_sent" to "تم إرسال البلاغ إلى المزوّد",
    "trying_server" to "جاري تجربة السيرفر %1\$d…",
    "stream_info" to "معلومات البث",
    "resume_q" to "المتابعة من حيث توقفت؟",
    "pause" to "إيقاف مؤقت",
    "more" to "المزيد",
    "search_online" to "بحث أونلاين",
    "subs_off_hint" to "البحث عن الترجمة أونلاين غير مفعّل — يمكن للمزوّد تفعيله من اللوحة (مفتاح OpenSubtitles).",
    "welcome_to" to "أهلاً بك في %1\$s",
    "server_down" to "السيرفر لا يستجيب حالياً.",
    "n_channels" to "%1\$d قناة",
    "n_titles" to "%1\$d فيلم",
    "n_shows" to "%1\$d مسلسل",
    "min_left" to "باقي %1\$d دقيقة",
    "new_this_week" to "جديد هذا الأسبوع",
    "open" to "فتح",
    "sports" to "رياضة",
    "yesterday" to "أمس",
    "today" to "اليوم",
    "tomorrow" to "غداً",
    "football_off" to "مباريات اليوم غير مفعّلة — يمكن للمزوّد تفعيلها من اللوحة.",
    "no_matches" to "لا توجد مباريات في هذا اليوم.",
    "live_now" to "مباشر الآن",
    "matches_today" to "مباريات اليوم",
    "match_channels" to "القنوات التي تعرض المباراة",
    "match_no_channel" to "لم يتم العثور على قناة في الدليل بعد — جرّب قسم الرياضة في البث المباشر.",
    "match_soon" to "المباراة تبدأ خلال 5 دقائق — اضغط للفتح",
    "change_server" to "تغيير السيرفر",
    "servers" to "السيرفرات",
    "server_n" to "سيرفر %1\$d",
    "one_server_only" to "يوجد سيرفر واحد فقط لهذا الحساب.",
    "downloaded_on" to "تم التنزيل",
    "downloading" to "جاري التنزيل",
    "download_failed" to "فشل",
    "remove" to "حذف",
    "change_playlist" to "تغيير القائمة",
    "one_playlist_only" to "توجد قائمة واحدة فقط في هذا الحساب.",
    "connected" to "متصل",
    "protected_pl" to "محمي",
    "mac_address" to "عنوان MAC",
    "device_key" to "مفتاح الجهاز",
    "use_code" to "لديك رمز تفعيل؟",
    "use_password" to "استخدم اسم المستخدم وكلمة المرور",
    "need_subscription" to "تحتاج اشتراك؟",
    "support_hint" to "تواصل مع %1\$s على واتساب — أرسل عنوان MAC ونفعّل هذا الجهاز.",
    "scan_whatsapp" to "امسح الرمز بكاميرا هاتفك لفتح المحادثة",
    "chat_whatsapp" to "محادثة واتساب",
    "no_whatsapp" to "رقم الدعم غير مضبوط بعد.",
    "crash_fix_expired" to "انتهى اشتراكك — جدّد أولاً.",
    "crash_fix_wait" to "انتظر %1\$d دقائق قبل المحاولة مجدداً.",
    "crash_fix_limit" to "وصلت الحد الأقصى (%1\$d في اليوم). حاول غداً.",
    "crash_fix_refused" to "السيرفر الاحتياطي لم يستجب — حاول بعد دقيقة.",
    "switched_to" to "تم التحويل إلى %1\$s",
    "preparing_line" to "جاري تجهيز السيرفر المؤقت، القنوات ستظهر خلال لحظات…",
    "rating" to "التقييم",
    "year" to "السنة",
    "length" to "المدة",
    "director" to "المخرج",
    "seasons" to "المواسم",
    "refreshing" to "جاري التحديث…",
    "whatsapp_support" to "دعم واتساب",
    "loading_playlist" to "جاري تحميل القائمة…",
    "prog_soon" to "يبدأ خلال 5 دقائق — اضغط للمشاهدة",
    "reminder_set" to "تم ضبط التذكير",
    "reminder_off" to "تم إلغاء التذكير",
    "speed_test" to "اختبار السرعة",
    "speed_start" to "ابدأ الاختبار",
    "speed_testing" to "جارٍ الاختبار… تحميل من سيرفرك",
    "speed_ping" to "استجابة السيرفر",
    "speed_download" to "سرعة التحميل",
    "speed_verdict_bad" to "بطيء جداً للبث — تحقق من الواي فاي أو جرّب سيرفراً آخر",
    "speed_verdict_sd" to "مناسب لقنوات SD؛ قد تتقطع HD",
    "speed_verdict_hd" to "جيد لـ HD",
    "speed_verdict_4k" to "ممتاز — جاهز لـ 4K",
    "speed_fail" to "تعذر الوصول إلى السيرفر",
    "speed_internet" to "سرعة الإنترنت",
    "speed_server" to "سيرفرك",
    "speed_jitter" to "تذبذب",
    "speed_again" to "أعد الاختبار",
    "speed_no_internet" to "لا يوجد إنترنت — تحقق من الواي فاي أو بيانات الهاتف",
    "speed_server_ok" to "البث يعمل بشكل طبيعي",
    "speed_server_bad" to "لم يصل أي بث — جرّب سيرفراً آخر",
    "speed_step_ping" to "استجابة السيرفر",
    "speed_step_down" to "سرعة الإنترنت",
    "speed_step_stream" to "بث السيرفر",
    "speed_hint" to "يقيس سرعة خط الإنترنت ويتأكد أن سيرفرك يرسل الفيديو. يستغرق حوالي 15 ثانية.",
    "record" to "تسجيل",
    "recording" to "جارٍ التسجيل…",
    "stop_recording" to "إيقاف",
    "recording_saved" to "تم حفظ التسجيل في التنزيلات",
    "record_scheduled" to "تمت جدولة التسجيل (اضغط مطولاً مرة أخرى للإلغاء)",
    "record_unscheduled" to "تم إلغاء التسجيل",
    "open_full" to "ملء الشاشة",
    "win_close" to "إغلاق",
    "win_min" to "تصغير",
    "shortcuts" to "المفاتيح: F ملء الشاشة · مسافة إيقاف · ↑↓ قناة · 0-9 رقم · Esc رجوع · M كتم · S ترجمة · A صوت",
    "checking_update" to "يتم التحقق من التحديثات…",
    "updated" to "تم التحديث",
    "device_id" to "معرّف الجهاز",
    "waiting_line" to "تم تسجيل هذا الكمبيوتر. اطلب من البائع إضافة قائمة لهذا المعرّف وستظهر هنا تلقائياً.",
    "copy" to "نسخ",
    "copied" to "تم النسخ",
    "mac_id_hint" to "أرسل معرّف الجهاز هذا للبائع"
)
    val HE = mapOf(
    "reorder_hint" to "גרור לסידור · סיום",
    "login_title" to "התחברות",
    "username" to "שם משתמש",
    "password" to "סיסמה",
    "sign_in" to "כניסה",
    "code_login" to "כניסה עם קוד הפעלה",
    "code" to "קוד בן 6 ספרות",
    "add_playlist" to "הוסף רשימה משלי",
    "playlist_name" to "שם הרשימה",
    "host" to "כתובת שרת (http://host:port)",
    "m3u_url" to "קישור M3U",
    "xtream" to "Xtream Codes",
    "m3u" to "קישור M3U",
    "save" to "שמור",
    "cancel" to "ביטול",
    "live" to "שידור חי",
    "movies" to "סרטים",
    "series" to "סדרות",
    "favorites" to "מועדפים",
    "continue_watching" to "המשך צפייה",
    "settings" to "הגדרות",
    "downloads" to "הורדות",
    "search" to "חיפוש",
    "crash_trial" to "ניסיון חירום",
    "crash_trial_hint" to "השרת נפל? קבל רשימה זמנית עכשיו.",
    "renew" to "חידוש בוואטסאפ",
    "expires_in" to "המנוי שלך מסתיים בעוד %1\$d ימים",
    "expired" to "המנוי שלך פג",
    "playlists" to "רשימות",
    "logout" to "התנתקות",
    "language" to "שפה",
    "theme" to "ערכת נושא",
    "theme_navy" to "כחול כהה",
    "theme_light" to "בהיר",
    "theme_amoled" to "שחור AMOLED",
    "subtitles" to "כתוביות",
    "subtitle_size" to "גודל כתוביות",
    "audio" to "שמע",
    "aspect" to "יחס תמונה",
    "speed" to "מהירות",
    "none" to "ללא",
    "pick_file" to "בחר קובץ כתוביות",
    "download" to "הורדה",
    "download_season" to "הורד עונה",
    "play" to "נגן",
    "resume" to "המשך",
    "episodes" to "פרקים",
    "season" to "עונה %1\$d",
    "all" to "הכל",
    "loading" to "טוען…",
    "error_network" to "לא ניתן להגיע לשרת",
    "error_login" to "שם משתמש או סיסמה שגויים",
    "error_blocked" to "החשבון חסום. פנה לספק.",
    "error_expired" to "המנוי פג. נא לחדש.",
    "hide" to "הסתר",
    "unhide" to "הצג",
    "move_up" to "הזז למעלה",
    "move_down" to "הזז למטה",
    "move_top" to "הזז להתחלה",
    "show_hidden" to "הצג מוסתרים",
    "next_episode" to "הפרק הבא",
    "sort" to "מיון",
    "sort_default" to "ברירת מחדל",
    "sort_az" to "א–ת",
    "sort_newest" to "חדש ביותר",
    "sort_rating" to "דירוג",
    "support" to "תמיכה",
    "messages" to "הודעות",
    "ok" to "אישור",
    "retry" to "נסה שוב",
    "no_items" to "אין כאן כלום עדיין",
    "wifi_only" to "הורדה רק ב-Wi-Fi",
    "delete" to "מחק",
    "playing_error" to "לא ניתן לנגן. מנסה שרת אחר…",
    "app_version" to "גרסה",
    "catchup" to "צפייה חוזרת",
    "now" to "עכשיו",
    "next" to "הבא",
    "lock_pin" to "נעל עם קוד",
    "unlock" to "הסר נעילה",
    "enter_pin" to "הזן קוד",
    "set_pin" to "קוד הורים (4 ספרות)",
    "wrong_pin" to "קוד שגוי",
    "recently_added" to "נוסף לאחרונה",
    "channel" to "ערוץ",
    "no_epg" to "אין נתוני לוח שידורים",
    "home_tab" to "ראשי",
    "lock" to "נעול",
    "add_favorite" to "הוסף למועדפים",
    "remove_favorite" to "הסר ממועדפים",
    "parental" to "בקרת הורים",
    "parental_hint" to "לחיצה ארוכה על קטגוריה ← נעל. קטגוריות נעולות מבקשות קוד זה.",
    "clear_history" to "נקה היסטוריה",
    "update_now" to "עדכן עכשיו",
    "update_hint" to "הורדה מחדש של רשימות הערוצים, הסרטים והסדרות מהשרת.",
    "hidden_hint" to "פריטים מוסתרים מוצגים עמומים; לחיצה ארוכה ← הצג.",
    "recently_viewed" to "נצפו לאחרונה",
    "multi_screen" to "מסך מפוצל",
    "expires" to "פג",
    "cast" to "שחקנים",
    "start_over" to "מההתחלה",
    "trailer" to "טריילר",
    "channels" to "ערוצים",
    "live_format" to "פורמט שידור חי",
    "external_player" to "פתח בנגן חיצוני",
    "pick_channel" to "בחר ערוץ",
    "change_language" to "שנה שפה",
    "change_layout" to "שנה פריסה",
    "hide_live" to "הסתר קטגוריות חי",
    "hide_vod" to "הסתר קטגוריות סרטים",
    "hide_series" to "הסתר קטגוריות סדרות",
    "clear_channels" to "נקה היסטוריית ערוצים",
    "clear_movies" to "נקה היסטוריית סרטים",
    "clear_series" to "נקה היסטוריית סדרות",
    "live_sort" to "מיון ערוצים",
    "change_player" to "שנה נגן",
    "external_players" to "נגנים חיצוניים",
    "automatic" to "אוטומטי",
    "time_format" to "פורמט שעה",
    "subtitle_settings" to "הגדרות כתוביות",
    "device_type" to "סוג מכשיר",
    "parental_onoff" to "בקרת הורים פועל/כבוי",
    "layout_large" to "גדול",
    "layout_normal" to "רגיל",
    "layout_compact" to "צפוף",
    "sort_number" to "לפי מספר",
    "format_hint" to "אוטומטי מנסה HLS ואז MPEG-TS כשערוץ נכשל.",
    "player_hint" to "אוטומטי משתמש ב-ExoPlayer ועובר ל-VLC כשלא ניתן לנגן.",
    "external_hint" to "פתח תמיד בנגן חיצוני (VLC / MX Player)",
    "automatic_hint" to "רענון רשימות אוטומטי כל 6 שעות",
    "subtitle_lang" to "שפת כתוביות מועדפת",
    "subtitle_color" to "צבע כתוביות",
    "crash_fix" to "תיקון תקלה",
    "crash_fix_q" to "השרת נפל? מעבר לשרת זמני ל־24 שעות, ואחר כך האפליקציה חוזרת לחשבון שלך לבד.",
    "crash_fix_active" to "תיקון תקלה פעיל — חזרה לחשבון שלך בעוד %1\$d שעות",
    "crash_fix_on" to "השרת הזמני הופעל ל־24 שעות",
    "crash_fix_off" to "תיקון תקלה לא זמין כרגע — פנה לתמיכה",
    "back_now" to "חזרה עכשיו",
    "exit_q" to "לצאת מ־9K Pro TV?",
    "exit" to "יציאה",
    "guide" to "לוח שידורים",
    "report_problem" to "דיווח על בעיה",
    "report_sent" to "הדיווח נשלח לספק",
    "trying_server" to "מנסה שרת %1\$d…",
    "stream_info" to "פרטי השידור",
    "resume_q" to "להמשיך מהמקום שעצרת?",
    "pause" to "השהיה",
    "more" to "עוד",
    "search_online" to "חיפוש אונליין",
    "subs_off_hint" to "חיפוש כתוביות אונליין כבוי — הספק יכול להפעיל אותו בפאנל (מפתח OpenSubtitles).",
    "welcome_to" to "ברוך הבא ל־%1\$s",
    "server_down" to "השרת שלך לא מגיב כרגע.",
    "n_channels" to "%1\$d ערוצים",
    "n_titles" to "%1\$d סרטים",
    "n_shows" to "%1\$d סדרות",
    "min_left" to "נותרו %1\$d דק׳",
    "new_this_week" to "חדש השבוע",
    "open" to "פתח",
    "sports" to "ספורט",
    "yesterday" to "אתמול",
    "today" to "היום",
    "tomorrow" to "מחר",
    "football_off" to "משחקי היום לא מופעלים — הספק יכול להפעיל בפאנל.",
    "no_matches" to "אין משחקים ביום זה.",
    "live_now" to "שידור חי",
    "matches_today" to "משחקי היום",
    "match_channels" to "ערוצים שמשדרים את המשחק",
    "match_no_channel" to "לא נמצא ערוץ בלוח עדיין — נסה את קטגוריית הספורט בשידור חי.",
    "match_soon" to "המשחק מתחיל בעוד 5 דקות — הקש לפתיחה",
    "change_server" to "החלפת שרת",
    "servers" to "שרתים",
    "server_n" to "שרת %1\$d",
    "one_server_only" to "יש רק שרת אחד לחשבון הזה.",
    "downloaded_on" to "הורד",
    "downloading" to "מוריד",
    "download_failed" to "נכשל",
    "remove" to "הסר",
    "change_playlist" to "החלפת פלייליסט",
    "one_playlist_only" to "יש רק פלייליסט אחד בחשבון הזה.",
    "connected" to "מחובר",
    "protected_pl" to "מוגן",
    "mac_address" to "כתובת MAC",
    "device_key" to "מפתח מכשיר",
    "use_code" to "יש לך קוד הפעלה?",
    "use_password" to "שם משתמש וסיסמה",
    "need_subscription" to "צריך מנוי?",
    "support_hint" to "דבר עם %1\$s בוואטסאפ — שלח את כתובת ה־MAC ונפעיל את המכשיר.",
    "scan_whatsapp" to "סרוק עם מצלמת הטלפון לפתיחת הצ׳אט",
    "chat_whatsapp" to "צ׳אט בוואטסאפ",
    "no_whatsapp" to "מספר התמיכה עדיין לא הוגדר.",
    "crash_fix_expired" to "המנוי פג — חדש קודם.",
    "crash_fix_wait" to "המתן %1\$d דקות לפני ניסיון נוסף.",
    "crash_fix_limit" to "הגעת למגבלה (%1\$d ביום). נסה מחר.",
    "crash_fix_refused" to "שרת הגיבוי לא ענה — נסה שוב בעוד דקה.",
    "switched_to" to "עברת אל %1\$s",
    "preparing_line" to "מכין את השרת הזמני, הערוצים יופיעו בעוד רגע…",
    "rating" to "דירוג",
    "year" to "שנה",
    "length" to "אורך",
    "director" to "במאי",
    "seasons" to "עונות",
    "refreshing" to "מרענן…",
    "whatsapp_support" to "תמיכה בוואטסאפ",
    "loading_playlist" to "טוען את הפלייליסט…",
    "prog_soon" to "מתחיל בעוד 5 דקות — הקש לצפייה",
    "reminder_set" to "התזכורת נקבעה",
    "reminder_off" to "התזכורת בוטלה",
    "speed_test" to "בדיקת מהירות",
    "speed_start" to "התחל בדיקה",
    "speed_testing" to "בודק… מוריד מהשרת שלך",
    "speed_ping" to "תגובת השרת",
    "speed_download" to "מהירות הורדה",
    "speed_verdict_bad" to "איטי מדי לשידור חי — בדוק את ה-Wi-Fi או נסה שרת אחר",
    "speed_verdict_sd" to "מתאים לערוצי SD; HD עלול להיתקע",
    "speed_verdict_hd" to "טוב ל-HD",
    "speed_verdict_4k" to "מצוין — מוכן ל-4K",
    "speed_fail" to "לא ניתן להגיע לשרת",
    "speed_internet" to "מהירות אינטרנט",
    "speed_server" to "השרת שלך",
    "speed_jitter" to "תנודתיות",
    "speed_again" to "בדוק שוב",
    "speed_no_internet" to "אין אינטרנט — בדוק את ה-Wi-Fi או חבילת הגלישה",
    "speed_server_ok" to "השידור עובד כרגיל",
    "speed_server_bad" to "לא התקבל שידור — נסה שרת אחר",
    "speed_step_ping" to "תגובת השרת",
    "speed_step_down" to "מהירות אינטרנט",
    "speed_step_stream" to "שידור מהשרת",
    "speed_hint" to "מודד את קו האינטרנט ובודק שהשרת שלך מספק וידאו. לוקח כ-15 שניות.",
    "record" to "הקלטה",
    "recording" to "מקליט…",
    "stop_recording" to "עצור",
    "recording_saved" to "ההקלטה נשמרה בהורדות",
    "record_scheduled" to "ההקלטה תוזמנה (לחיצה ארוכה שוב לביטול)",
    "record_unscheduled" to "ההקלטה בוטלה",
    "open_full" to "מסך מלא",
    "win_close" to "סגור",
    "win_min" to "מזער",
    "shortcuts" to "מקשים: F מסך מלא · רווח השהיה · ↑↓ ערוץ · 0-9 מספר · Esc חזרה · M השתק · S כתוביות · A שמע",
    "checking_update" to "בודק עדכונים…",
    "updated" to "עודכן",
    "device_id" to "מזהה מכשיר",
    "waiting_line" to "המחשב נרשם. בקש מהמוכר להוסיף רשימה למזהה הזה והיא תופיע כאן לבד.",
    "copy" to "העתק",
    "copied" to "הועתק",
    "mac_id_hint" to "שלח את מזהה המכשיר למוכר"
)

    fun lang(pref: String): String {
        if (pref.isNotEmpty()) return pref
        val l = java.util.Locale.getDefault().language
        return when (l) { "ar" -> "ar"; "iw", "he" -> "iw"; else -> "en" }
    }
    fun isRtl(lang: String) = lang == "ar" || lang == "iw"
    fun get(lang: String, key: String): String = (when (lang) { "ar" -> AR[key]; "iw" -> HE[key]; else -> null }) ?: EN[key] ?: key
}

val LocalLang = compositionLocalOf { "en" }

@androidx.compose.runtime.Composable
fun T(key: String): String = Strings.get(LocalLang.current, key)
@androidx.compose.runtime.Composable
fun T(key: String, vararg args: Any): String { val l = LocalLang.current; return fmt(Strings.get(l, key), args) }
fun fmt(s: String, args: Array<out Any>): String = try { String.format(s, *args) } catch (e: Exception) { s }
